/* Select component */
const countries = [
  { value: "ABW", label: "Aruba"},
  { value: "AFG", label: "Afghanistan"},
  { value: "AGO", label: "Angola"},
  { value: "ALB", label: "Albania"},
  { value: "AND", label: "Andorra"},
  { value: "ARB", label: "Arab World"},
  { value: "ARE", label: "United Arab Emirates"},
  { value: "ARG", label: "Argentina"},
  { value: "ARM", label: "Armenia"},
  { value: "ASM", label: "American Samoa"},
  { value: "ATG", label: "Antigua and Barbuda"},
  { value: "AUS", label: "Australia"},
  { value: "AUT", label: "Austria"},
  { value: "AZE", label: "Azerbaijan"},
  { value: "BDI", label: "Burundi"},
  { value: "BEL", label: "Belgium"},
  { value: "BEN", label: "Benin"},
  { value: "BFA", label: "Burkina Faso"},
  { value: "BGD", label: "Bangladesh"},
  { value: "BGR", label: "Bulgaria"},
  { value: "BHR", label: "Bahrain"},
  { value: "BHS", label: "Bahamas"},
  { value: "BIH", label: "Bosnia and Herzegovina"},
  { value: "BLR", label: "Belarus"},
  { value: "BLZ", label: "Belize"},
  { value: "BMU", label: "Bermuda"},
  { value: "BOL", label: "Bolivia"},
  { value: "BRA", label: "Brazil"},
  { value: "BRB", label: "Barbados"},
  { value: "BRN", label: "Brunei Darussalam"},
  { value: "BTN", label: "Bhutan"},
  { value: "BWA", label: "Botswana"},
  { value: "CAF", label: "Central African Republic"},
  { value: "CAN", label: "Canada"},
  { value: "CEB", label: "Central Europe and the Baltics"},
  { value: "CHE", label: "Switzerland"},
  { value: "CHI", label: "Channel Islands"},
  { value: "CHL", label: "Chile"},
  { value: "CHN", label: "China"},
  { value: "CIV", label: "Cote d'Ivoire"},
  { value: "CMR", label: "Cameroon"},
  { value: "COD", label: "Dem Congo"},
  { value: "COG", label: "Rep Congo"},
  { value: "COL", label: "Colombia"},
  { value: "COM", label: "Comoros"},
  { value: "CPV", label: "Cabo Verde"},
  { value: "CRI", label: "Costa Rica"},
  { value: "CSS", label: "Caribbean small states"},
  { value: "CUB", label: "Cuba"},
  { value: "CUW", label: "Curacao"},
  { value: "CYM", label: "Cayman Islands"},
  { value: "CYP", label: "Cyprus"},
  { value: "CZE", label: "Czech Republic"},
  { value: "DEU", label: "Germany"},
  { value: "DJI", label: "Djibouti"},
  { value: "DMA", label: "Dominica"},
  { value: "DNK", label: "Denmark"},
  { value: "DOM", label: "Dominican Republic"},
  { value: "DZA", label: "Algeria"},
  { value: "EAP", label: "East Asia & Pacific (excluding high income)"},
  { value: "ESP", label: "Espostan"},
  { value: "EAR", label: "Early-demographic dividend"},
  { value: "EAS", label: "East Asia & Pacific"},
  { value: "ECA", label: "Europe & Central Asia (excluding high income)"},
  { value: "ECS", label: "Europe & Central Asia"},
  { value: "ECU", label: "Ecuador"},
  { value: "EGY", label: "Egypt Arab Rep."},
  { value: "EMU", label: "Euro area"},
  { value: "ERI", label: "Eritrea"},
  { value: "ESP", label: "Spain"},
  { value: "EST", label: "Estonia"},
  { value: "ETH", label: "Ethiopia"},
  { value: "EUU", label: "European Union"},
  { value: "FIN", label: "Finland"},
  { value: "FJI", label: "Fiji"},
  { value: "FRA", label: "France"},
  { value: "FRO", label: "Faroe Islands"},
  { value: "FSM", label: "Micronesia Fed. Sts."},
  { value: "GAB", label: "Gabon"},
  { value: "GBR", label: "United Kingdom"},
  { value: "GEO", label: "Georgia"},
  { value: "GHA", label: "Ghana"},
  { value: "GIB", label: "Gibraltar"},
  { value: "GIN", label: "Guinea"},
  { value: "GMB", label: "Gambia"},
  { value: "GNB", label: "Guinea-Bissau"},
  { value: "GNQ", label: "Equatorial Guinea"},
  { value: "GRC", label: "Greece"},
  { value: "GRD", label: "Grenada"},
  { value: "GRL", label: "Greenland"},
  { value: "GTM", label: "Guatemala"},
  { value: "GUM", label: "Guam"},
  { value: "GUY", label: "Guyana"},
  { value: "HIC", label: "High income"},
  { value: "HKG", label: "Hong Kong SAR China"},
  { value: "HND", label: "Honduras"},
  { value: "HPC", label: "Heavily indebted poor countries (HIPC)"},
  { value: "HRV", label: "Croatia"},
  { value: "HTI", label: "Haiti"},
  { value: "HUN", label: "Hungary"},
  { value: "IBD", label: "IBRD only"},
  { value: "IBT", label: "IDA & IBRD total"},
  { value: "IDA", label: "IDA total"},
  { value: "IDB", label: "IDA blend"},
  { value: "IDN", label: "Indonesia"},
  { value: "IDX", label: "IDA only"},
  { value: "IMN", label: "Isle of Man"},
  { value: "IND", label: "India"},
  { value: "INX", label: "Not classified"},
  { value: "IRL", label: "Ireland"},
  { value: "IRN", label: "Iran Islamic Rep."},
  { value: "IRQ", label: "Iraq"},
  { value: "ISL", label: "Iceland"},
  { value: "ISR", label: "Israel"},
  { value: "ITA", label: "Italy"},
  { value: "JAM", label: "Jamaica"},
  { value: "JOR", label: "Jordan"},
  { value: "JPN", label: "Japan"},
  { value: "KAZ", label: "Kazakhstan"},
  { value: "KEN", label: "Kenya"},
  { value: "KGZ", label: "Kyrgyz Republic"},
  { value: "KHM", label: "Cambodia"},
  { value: "KIR", label: "Kiribati"},
  { value: "KNA", label: "St. Kitts and Nevis"},
  { value: "KOR", label: "Korea Rep."},
  { value: "KWT", label: "Kuwait"},
  { value: "LAC", label: "Latin America & Caribbean (excluding high income)"},
  { value: "LAO", label: "Lao PDR"},
  { value: "LBN", label: "Lebanon"},
  { value: "LBR", label: "Liberia"},
  { value: "LBY", label: "Libya"},
  { value: "LCA", label: "St. Lucia"},
  { value: "LCN", label: "Latin America & Caribbean"},
  { value: "LDC", label: "Least developed countries: UN classification"},
  { value: "LIC", label: "Low income"},
  { value: "LIE", label: "Liechtenstein"},
  { value: "LKA", label: "Sri Lanka"},
  { value: "LMC", label: "Lower middle income"},
  { value: "LMY", label: "Low & middle income"},
  { value: "LSO", label: "Lesotho"},
  { value: "LTE", label: "Late-demographic dividend"},
  { value: "LTU", label: "Lithuania"},
  { value: "LUX", label: "Luxembourg"},
  { value: "LVA", label: "Latvia"},
  { value: "MAC", label: "Macao SAR China"},
  { value: "MAF", label: "St. Martin (French part)"},
  { value: "MAR", label: "Morocco"},
  { value: "MCO", label: "Monaco"},
  { value: "MDA", label: "Moldova"},
  { value: "MDG", label: "Madagascar"},
  { value: "MDV", label: "Maldives"},
  { value:  "MEA", label: "Middle East & North Africa"},
  { value: "MEX", label: "Mexico"},
  { value: "MHL", label: "Marshall Islands"},
  { value: "MIC", label: "Middle income"},
  { value:  "FYR", label: "Macedonia"},
  { value: "MLI", label: "Mali"},
  { value: "MLT", label: "Malta"},
  { value: "MMR", label: "Myanmar"},
  { value: "MNA", label: "Middle East & North Africa (excluding high income)"},
  { value: "MNE", label: "Montenegro"},
  { value: "MNG", label: "Mongolia"},
  { value: "MNP", label: "Northern Mariana Islands"},
  { value: "MOZ", label: "Mozambique"},
  { value: "MRT", label: "Mauritania"},
  { value: "MUS", label: "Mauritius"},
  { value: "MWI", label: "Malawi"},
  { value: "MYS", label: "Malaysia"},
  { value: "NAC", label: "North America"},
  { value: "NAM", label: "Namibia"},
  { value: "NCL", label: "New Caledonia"},
  { value: "NER", label: "Niger"},
  { value: "NGA", label: "Nigeria"},
  { value: "NIC", label: "Nicaragua"},
  { value: "NLD", label: "Netherlands"},
  { value: "NOR", label: "Norway"},
  { value: "NPL", label: "Nepal"},
  { value: "NRU", label: "Nauru"},
  { value: "NZL", label: "New Zealand"},
  { value: "OED", label: "OECD members"},
  { value: "OMN", label: "Oman"},
  { value: "OSS", label: "Other small states"},
  { value: "PAK", label: "Pakistan"},
  { value: "PAN", label: "Panama"},
  { value: "PER", label: "Peru"},
  { value: "PHL", label: "Philippines"},
  { value: "PLW", label: "Palau"},
  { value: "PNG", label: "Papua New Guinea"},
  { value: "POL", label: "Poland"},
  { value: "PRE", label: "Pre-demographic dividend"},
  { value: "PRI", label: "Puerto Rico"},
  { value: "PRK", label: "Korea Dem. People’s Rep."},
  { value: "PRT", label: "Portugal"},
  { value: "PRY", label: "Paraguay"},
  { value: "PSE", label: "West Bank and Gaza"},
  { value: "PSS", label: "Pacific island small states"},
  { value: "PST", label: "Post-demographic dividend"},
  { value: "PYF", label: "French Polynesia"},
  { value: "QAT", label: "Qatar"},
  { value: "ROU", label: "Romania"},
  { value: "RUS", label: "Russian Federation"},
  { value: "RWA", label: "Rwanda"},
  { value: "SAS", label: "South Asia"},
  { value: "SAU", label: "Saudi Arabia"},
  { value: "SDN", label: "Sudan"},
  { value: "SEN", label: "Senegal"},
  { value: "SGP", label: "Singapore"},
  { value: "SLB", label: "Solomon Islands"},
  { value: "SLE", label: "Sierra Leone"},
  { value: "SLV", label: "El Salvador"},
  { value: "SMR", label: "San Marino"},
  { value: "SOM", label: "Somalia"},
  { value: "SRB", label: "Serbia"},
  { value: "SSA", label: "Sub-Saharan Africa (excluding high income)"},
  { value: "SSD", label: "South Sudan"},
  { value: "SSF", label: "Sub-Saharan Africa"},
  { value: "SST", label: "Small states"},
  { value: "STP", label: "Sao Tome and Principe"},
  { value: "SUR", label: "Suriname"},
  { value: "SVK", label: "Slovak Republic"},
  { value: "SVN", label: "Slovenia"},
  { value: "SWE", label: "Sweden"},
  { value: "SWZ", label: "Eswatini"},
  { value: "SXM", label: "Sint Maarten (Dutch part)"},
  { value: "SYC", label: "Seychelles"},
  { value: "SYR", label: "Syrian Arab Republic"},
  { value: "TCA", label: "Turks and Caicos Islands"},
  { value: "TCD", label: "Chad"},
  { value: "TEA", label: "East Asia & Pacific (IDA & IBRD countries)"},
  { value: "TEC", label: "Europe & Central Asia (IDA & IBRD countries)"},
  { value: "TGO", label: "Togo"},
  { value: "THA", label: "Thailand"},
  { value: "TJK", label: "Tajikistan"},
  { value: "TKM", label: "Turkmenistan"},
  { value: "TLA", label: "Latin America & the Caribbean (IDA & IBRD countries)"},
  { value: "TLS", label: "Timor-Leste"},
  { value: "TMN", label: "Middle East & North Africa (IDA & IBRD countries)"},
  { value: "TON", label: "Tonga"},
  { value: "TSA", label: "South Asia (IDA & IBRD)"},
  { value: "TSS", label: "Sub-Saharan Africa (IDA & IBRD countries)"},
  { value: "TTO", label: "Trinidad and Tobago"},
  { value: "TUN", label: "Tunisia"},
  { value: "TUR", label: "Turkey"},
  { value: "TUV", label: "Tuvalu"},
  { value: "TZA", label: "Tanzania"},
  { value: "UGA", label: "Uganda"},
  { value: "UKR", label: "Ukraine"},
  { value: "UMC", label: "Upper middle income"},
  { value: "URY", label: "Uruguay"},
  { value: "USA", label: "United States"},
  { value: "UZB", label: "Uzbekistan"},
  { value: "VCT", label: "St. Vincent and the Grenadines"},
  { value: "VEN", label: "Venezuela"},
  { value: "VGB", label: "British Virgin Islands"},
  { value: "VIR", label: "Virgin Islands (U.S.)"},
  { value: "VNM", label: "Vietnam"},
  { value: "VUT", label: "Vanuatu"},
  { value: "WLD", label: "World"},
  { value: "WSM", label: "Samoa"},
  { value: "XKX", label: "Kosovo"},
  { value: "YEM", label: "Yemen"},
  { value: "ZAF", label: "South Africa"},
  { value: "ZMB", label: "Zambia"},
  { value: "ZWE", label: "Zimbabwe"}
]

export default countries;
